apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-rolling-update
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rahul108/Module-3-deployment.git
    targetRevision: HEAD
    path: deployment/k8s/rolling-update
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
