apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-rolling
  labels:
    app: node-app
    strategy: rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: node-app
      strategy: rolling
  template:
    metadata:
      labels:
        app: node-app
        strategy: rolling
    spec:
      containers:
      - name: node-app
        image: prefixsarker/node-express-app:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
