apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-canary
  labels:
    app: node-app
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
      version: canary
  template:
    metadata:
      labels:
        app: node-app
        version: canary
    spec:
      containers:
      - name: node-app
        image: prefixsarker/node-express-app:v1.1.0
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
