apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-green
  labels:
    app: node-app
    version: green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: node-app
      version: green
  template:
    metadata:
      labels:
        app: node-app
        version: green
    spec:
      containers:
      - name: node-app
        image: your-dockerhub-username/node-express-app:v1.1.0
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
