apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: node-app
spec:
  selector:
    app: node-app
    version: blue
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-preview-service
  labels:
    app: node-app
spec:
  selector:
    app: node-app
    version: green
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
